DROP DATABASE IF EXISTS LIBMS;

CREATE DATABASE LIBMS;

USE LIBMS;

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK ( 
	Isbn	VARCHAR(10) NOT NULL,
	Title	VARCHAR(255) NOT NULL,
	CONSTRAINT pk_Book PRIMARY KEY (Isbn)
);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR (
	Author_id	VARCHAR(5) NOT NULL,
	Name		VARCHAR(50) NOT NULL,
	CONSTRAINT pk_author_id PRIMARY KEY (Author_id)
);

DROP TABLE IF EXISTS BOOK_AUTHOR;
CREATE TABLE BOOK_AUTHOR (
	Author_id	VARCHAR(5) NOT NULL,
	Isbn		VARCHAR(10) NOT NULL,
	CONSTRAINT pk_book_author PRIMARY KEY (Author_id, Isbn),
	CONSTRAINT fk_book_isbn FOREIGN KEY (Isbn) REFERENCES BOOK(Isbn),
	CONSTRAINT fk_author_id FOREIGN KEY (Author_id) REFERENCES AUTHOR(Author_id)
);


DROP TABLE IF EXISTS BORROWER;
CREATE TABLE BORROWER (
	Card_id 	VARCHAR(8) NOT NULL,
	Ssn			CHAR(9),
	Fname		VARCHAR(50) NOT NULL,
	Lname		VARCHAR(50) NOT NULL,
	Email		VARCHAR(128),
	Address		VARCHAR(100),
	City		VARCHAR(50),
	State		CHAR(2),
	PostalCode	VARCHAR(10),
	PhoneNumber	VARCHAR(10),
	CONSTRAINT pk_borrower PRIMARY KEY (Card_id),
	CONSTRAINT uk_borrower_ssn UNIQUE (Ssn)
);

DROP TABLE IF EXISTS LOAN;
CREATE TABLE LOAN (
	Loan_id		INT NOT NULL,
	Isbn		VARCHAR(10) NOT NULL,
	Card_id		VARCHAR(8) NOT NULL,
	Date_out	DATE NOT NULL,
	Date_due	DATE,
	Date_in		DATE,
	CONSTRAINT pk_loan PRIMARY KEY (Loan_id),
	CONSTRAINT fk_loan_isbn FOREIGN KEY (Isbn) REFERENCES BOOK(Isbn),
	CONSTRAINT fk_loan_card_id FOREIGN KEY (Card_id) REFERENCES BORROWER(Card_id)
	
);

DROP TABLE IF EXISTS FINE;
CREATE TABLE FINE (
	Loan_id		INT NOT NULL,
	Fine_amt	DECIMAL(8,2) NOT NULL,
	Paid		BOOLEAN NOT NULL DEFAULT FALSE,
	CONSTRAINT pk_fine PRIMARY KEY (Loan_id),
	CONSTRAINT fk_fine_id FOREIGN KEY (Loan_id) REFERENCES LOAN(Loan_id)
);